### PR TITLE
Release v2.0

### PR DESCRIPTION
**Pull request by HajimeKawahara**
This is PR for release v2.0 to `master` branch.
You can check the update by reading [here](https://github.com/HajimeKawahara/exojax/milestone/9)

@ykawashima Can you check an example for spec+photo, described [here](https://secondearths.sakura.ne.jp/exojax/develop/examples/index.html), or directly the code at `exojax/examples/spec_with_photo.py`

@YuiKasagi Can you update #401 (only documentation)?

@sh-tada Can you make a brief example for JWST transmission NUTS, similar as  `exojax/examples/spec_with_photo.py`
 for sphinx-gallery? 

I will add more documentations. We plan to release v2.0 on 3/26.

### CODE REVIEW

**Comment by ykawashima** [comment]
Thank you very much! While checking, I happened to notice that newly downloading the HITEMP database failed, at least in my environment. Note that using the previously created file still works. This issue occurred with ExoJAX==2.0 and radis==0.15.2, as well as ExoJAX==1.5.1 and radis==0.15. Could you please check if this happens in other environments as well? Thank you.

Sample code:
```
from exojax.spec.api import MdbHitemp
mdb_ch4 = MdbHitemp("/home/kawashima/database/CH4/06_HITEMP2020/06_HITEMP2020.par.bz2", nurange=[4300,4400], gpu_transfer=False)
print("aa")
mdb_ch4 = MdbHitemp(".database/CH4", nurange=[4300,4400], gpu_transfer=False)
print("aa")
```

Error:
```
Downloading 06_HITEMP2020.par.bz2 for CH4 (1/1).
Traceback (most recent call last):
 File "/home/moo/exojax/examples/hitemp.py", line 7, in <module>
  mdb_ch4 = MdbHitemp(".database/CH4", nurange=[4300,4400], gpu_transfer=False)
 File "/home/moo/anaconda3/lib/python3.9/site-packages/ExoJAX-2.0-py3.9.egg/exojax/spec/api.py", line 777, in __init__
  self.download_and_parse(download_urls, download_files)
 File "/home/moo/anaconda3/lib/python3.9/site-packages/radis/api/dbmanager.py", line 435, in download_and_parse
  download_and_parse_one_file(urlname, local_file, Ndownload)
 File "/home/moo/anaconda3/lib/python3.9/site-packages/radis/api/dbmanager.py", line 400, in download_and_parse_one_file
  Nlines = self.parse_to_local_file(
 File "/home/moo/anaconda3/lib/python3.9/site-packages/radis/api/hitempapi.py", line 315, in parse_to_local_file
  linereturnformat = self.get_linereturn_format(opener, urlname, columns)
 File "/home/moo/anaconda3/lib/python3.9/site-packages/radis/api/hitempapi.py", line 277, in get_linereturn_format
  gfile.readinto(b)
 File "/home/moo/anaconda3/lib/python3.9/bz2.py", line 193, in readinto
  return self._buffer.readinto(b)
 File "/home/moo/anaconda3/lib/python3.9/_compression.py", line 68, in readinto
  data = self.read(len(byte_view))
 File "/home/moo/anaconda3/lib/python3.9/_compression.py", line 103, in read
  data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream
```

**Comment by HajimeKawahara** [comment]
@ykawashima Thank you! Yes, this is because, recently, logging into HITRAN has become mandatory to access HITEMP files, causing issues with automated HITEMP file retrieval by RADIS. Currently the develop version of RADIS solved this problem (https://github.com/radis/radis/issues/717), but if we use the current version of radis, we need the manual download. 
I added the explanation in `Warning` of the top page of the ExoJAX document. https://secondearths.sakura.ne.jp/exojax/

**Comment by ykawashima** [comment]
Ah, I see. Thank you!

File: examples/spec_with_photo.py [hunk 1]
```diff
@@ -0,0 +1,498 @@
...
+import numpy as np
+import jax.numpy as jnp
+import matplotlib.pyplot as plt
+from exojax.spec.specop import SopPhoto
+from exojax.test.emulate_spec import sample_emission_spectrum
+from exojax.utils.grids import wavenumber_grid
+from exojax.utils.instfunc import resolution_to_gaussian_std
+
+from jax import jit
+
```
Comment (ykawashima) [inline examples/spec_with_photo.py:21]: This is just a suggestion, but to ensure the existence of the output directories
```suggestion
+import os
+os.makedirs("./output", exist_ok=True)
+os.makedirs("./output_bn", exist_ok=True)
```

File: examples/spec_with_photo.py [hunk 2]
```diff
@@ -0,0 +1,498 @@
...
+mdb_h2o = MdbExomol(
+    ".database/H2O/1H2-16O/POKAZATEL", nurange=nu_grid_photo, gpu_transfer=False
+)
+mdb_co = MdbExomol(
+    ".database/CO/12C-16O/Li2015", nurange=nu_grid_photo, gpu_transfer=False
+)
+mdb_ch4 = MdbHitemp(".database/CH4", nurange=nu_grid_photo, gpu_transfer=False)
+
+molmasses = jnp.array([mdb_h2o.molmass, mdb_ch4.molmass, mdb_co.molmass])
+molmasses = jnp.array([mdb_h2o.molmass])
```
Comment (ykawashima) [inline examples/spec_with_photo.py:95]: This line is not needed:
```suggestion
```

**Review by ykawashima — APPROVED** [review]
Thank you very much! I have confirmed that ``spec_with_photo.py`` works.

File: src/exojax/utils/photometry.py [hunk 3]
```diff
@@ -0,0 +1,145 @@
+import numpy as np
+import jax.numpy as jnp
+from exojax.spec.unitconvert import wav2nu
+from exojax.utils.constants import ccgs
+from exojax.utils.url import url_svo_filter
+
```
Comment (ykawashima) [inline src/exojax/utils/photometry.py:6]:
```suggestion
from jax.scipy.integrate import trapezoid
```

File: src/exojax/utils/photometry.py [hunk 4]
```diff
@@ -0,0 +1,145 @@
...
+        nu_grid_filter (array): wavenumber grid (cm-1)
+        transmission_filter (array): transmission filter (dimensionless, 0 to 1)
+        f0_nu_cgs (float): zero magnitude flux in the unit of erg/s/cm^2/cm-1
+        factor (float): factor to prevent numerical error. Defaults to 1.0e20.
+    """
+
+    logfactor = jnp.log10(factor)
+    integrated_flux = jnp.trapezoid(
+        (flux_filter * factor) * transmission_filter, nu_grid_filter
+    ) / jnp.trapezoid(transmission_filter, nu_grid_filter)
```
Comment (ykawashima) [inline src/exojax/utils/photometry.py:24]: To reflect the deprecation of jnp.trapezoid 
```suggestion
    integrated_flux = trapezoid(
        (flux_filter * factor) * transmission_filter, nu_grid_filter
    ) / trapezoid(transmission_filter, nu_grid_filter)
```

**Review by YuiKasagi — APPROVED** [review]
Thank you! I have confirmed that both `unittests` and `integration` work in my environment with radis develop branch.

**Review by kemasuda — APPROVED** [review]

File: src/exojax/utils/photometry.py (hunk 4 above)
Comment (HajimeKawahara) [reply src/exojax/utils/photometry.py:24]: but maybe it's too new?

Comment (ykawashima) [reply src/exojax/utils/photometry.py:24]: Thank you for your reply! At least in my environment, I encountered the following error when using ``jnp.trapezoid`` with JAX==0.4.16.  So, I followed [this implementation](https://github.com/HajimeKawahara/exojax/pull/476), which was also recommended by [JAX](https://docs.jax.dev/en/latest/changelog.html#jax-0-4-16-sept-18-2023) as you cited. Given that ``jnp.trapz`` was just deprecated in JAX==0.4.16, ``jnp.trapezoid`` is the older version of `jnp.trapz``?

```jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/moo/exojax/examples/spec_with_photo.py", line 368, in <module>
    Kmag_model = fphoto(
  File "/home/moo/exojax/examples/spec_with_photo.py", line 328, in fphoto
    mag = sop_photo.apparent_magnitude(Fobs)
  File "/home/moo/anaconda3/lib/python3.9/site-packages/ExoJAX-2.0-py3.9.egg/exojax/spec/specop.py", line 161, in apparent_magnitude
    return apparent_magnitude(
  File "/home/moo/anaconda3/lib/python3.9/site-packages/ExoJAX-2.0-py3.9.egg/exojax/utils/photometry.py", line 23, in apparent_magnitude
    integrated_flux = jnp.trapezoid(
  File "/home/moo/anaconda3/lib/python3.9/site-packages/jax/_src/deprecations.py", line 53, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.numpy' has no attribute 'trapezoid'```

**Comment by astrostevanus** [comment]
Thank you for the PR. I tried to install it as if I was a new user. So I tried it in a new conda environment (Python 3.9.21), but I got an error. 

It seems that {'specutils'} requires  scipy>=1.14 but scipy 1.14.0 would require Python >=3.10. I am wondering if anyone else is experiencing this issue.

**Comment by HajimeKawahara** [comment]
@astrostevanus Thanks for the report! I removed `astropy` from the requirement. Can you try it again?

**Comment by astrostevanus** [comment]
Thank you for the update! I have tried it but it is still an issue. But I found that conda by default (Python 3.9.21) installed specutils 2.0.0rc1 which require scipy 1.14 that somehow only works on Python 3.10. So I "downgrade" the specutils by "pip install specutils --upgrade" and I can install Exojax seamlessly. As a reference this is how I create my conda environment and install the dependency for Exojax:

conda create -n exo39 python=3.9 -y
pip install astroquery  vaex-astro msgpack ndindex pybind11 vaex cython shapely
conda install -c conda-forge hdf5 pytables geos
pip install numpyro[cuda]==0.13.2 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install specutils --upgrade


I have also tried to install it on Python 3.10, and found no issue. I can confirm `unittest` works in my env.

**Review by astrostevanus — APPROVED** [review]

**Review by KoHosokawa — APPROVED** [review]
Thank you for the PR! I confirmed that those changes are no problem with my environment.

**Review by sh-tada — APPROVED** [review]
